### ISSUE TITLE
Keep popover open and interactive

### ISSUE THREAD

**Issue by BeckhamL** [joejordanbrown/popover#121]
Thanks for making this component, it works seamlessly and intuitively. 

My popover has multiple buttons that a user can select. Is there a way that the popover can stay open as the user clicks on the various buttons? I would only like the popover to close when the user clicks the 'close' button or outside the popover for example.

**Comment by joejordanbrown** [comment]
@BeckhamL 

Thank you, I'm happy so many people find it useful.

I think this example I've made [here](https://stackblitz.com/edit/mde-popover-button-close?file=app%2Fapp.component.html) showcases how to disable the on click close event and also shows a child popover to show that it works having a popover inside another popover. 

All the options used can be found in the documentation found [here ](https://github.com/joejordanbrown/popover/blob/master/projects/material-extended/mde/src/lib/popover/popover.md).

If you have time you could create a pull request showing some creative examples, in an example folder on this repo, they can also be included in the demo app and I will deploy them which I'm sure would help many people see the potential use cases of this popover.
