### ISSUE TITLE
Add argument "backdrop disable"

### ISSUE THREAD

**Issue by djadjavit** [joejordanbrown/popover#41]
#### Bug, feature request, or proposal:
Add argument "backdrop disable"

#### What is the expected behaviour?
if this argument true, cdk-overlay-backdrop not show

#### Other Comments
I need to disable backdrop, it would be great if it were possible to disable not only the click on the backdrop, but the backdrop itself. Or perhaps you know how to do it now? Anyway, thanks for the good library.

**Comment by joejordanbrown** [comment]
@djadjavit 

The backdrop is only rendered with `mdePopoverTriggerOn="click"`, you can see that here [popover-trigger.ts#L359-L362](https://github.com/material-extended/mde/blob/master/projects/material-extended/mde/src/lib/popover/popover-trigger.ts#L359-L362), you shouldn't need to disable it seeing as when you use other events it's not initiated.

I can see that it might be useful to have an option to enable it for custom events though.
