### ISSUE TITLE
Opened boolean

### ISSUE THREAD

**Issue by madzinah** [joejordanbrown/popover#44]
#### Bug, feature request, or proposal:
Feature Request

#### What is the expected behaviour?
Mat-Menu is giving a boolean _opened_ to give the information whether the menu is open, it could be nice to have a _opened_ boolean variable on the MdePopoverTrigger like it exists already on the MatMenuTrigger : https://material.angular.io/components/menu/api#MatMenuTrigger

#### What is the current behaviour?
There is only the event _opened_ and _closed_ we have to subscribe to if we want to be noticed of the change of state of the Popover.

#### What is the use-case or motivation for changing an existing behaviour?
Simplicity as the boolean avoid to subscribe to 2 events.
Also, the material2 API works now (at least Mat-Menu-Trigger) with a _opened_ boolean variable and not with the events, so maybe consistency.

**Comment by joejordanbrown** [comment]
@madzinah 

Thanks for the feature request. Sorry about the slow reply.

After reviewing the source, I can see this feature already exists but is not documented, see source [popover-trigger.ts#L189](https://github.com/material-extended/mde/blob/488d556ae881b39efa4656797d1ad3caabc5349b/projects/material-extended/mde/src/lib/popover/popover-trigger.ts#L189).

Using `popoverTrigger.popoverOpen` will return `true` or `false` for popover open status.

```javascript
popoverTrigger.popoverOpen ? 'opened' : 'closed'
```

```html
<button mat-raised-button color="primary"
  [mdePopoverTriggerFor]="popover"
  mdePopoverTriggerOn="click" #popoverTrigger="mdePopoverTrigger">
  Show Popover
</button>

<mde-popover #popover="mdePopover" [mdePopoverOverlapTrigger]="false">
  <mat-card style="max-width: 300px">
    <mat-card-content>
    A material design popover component created using Angular version 7 with the Angular CDK.
    </mat-card-content>
  </mat-card>
</mde-popover>
```

I've added this example to our public popover example on StackBlitz https://stackblitz.com/edit/mde-popover?file=app%2Fapp.component.html

Let me know if you have any questions.

---------------------------

This feature request has made me think that possibly there should be a way to set the popover open using an attribute which could also allow two-way binding.

**Hardcoded boolean**

```html
<button mat-raised-button color="primary"
  [mdePopoverTriggerFor]="popover"
  mdePopoverTriggerOn="click" mdPopoverOpen="true">
  Show Popover
</button>
```

**Set with variable, one-way binding.**

```javascript
popoverOpen = true;
```

```html
<button mat-raised-button color="primary"
  [mdePopoverTriggerFor]="popover"
  mdePopoverTriggerOn="click" [mdPopoverOpen]="popoverOpen">
  Show Popover
</button>
```

**Set with variable, two-way binding.**

```javascript
popoverOpen = true;
```

```html
<button mat-raised-button color="primary"
  [mdePopoverTriggerFor]="popover"
  mdePopoverTriggerOn="click" [(mdPopoverOpen)]="popoverOpen">
  Show Popover
</button>
```
