### ISSUE TITLE
Popover does not work with fullscreen

### ISSUE THREAD

**Issue by kkseven07** [joejordanbrown/popover#59]
Seems like popover doesn't appear in fullscreen mode. Any solutions?

[Stackblitz example](https://stackblitz.com/edit/ngx-graph-demo-pm8i1t)

Nodes of the tree are the triggers to show the popover.

**Comment by joejordanbrown** [comment]
@kkseven07 

After looking into this, I found that the `@angular/cdk` overlay requires you to use the `FullscreenOverlayContainer` for the overlay to work correctly in fullscreen mode. See here https://material.angular.io/cdk/overlay/overview#full-screen-overlays for more info.

I've updated your StackBlitz demo with the required provider https://stackblitz.com/edit/ngx-graph-demo-mde-popover-fullscreen-example?file=src/app/app.module.ts, let me know if you have any other issues. 

If you have time, you are welcome to update our documentation with notes on using fullscreen and the popover 🙂
