### ISSUE TITLE
An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by PTC-JoshuaMatthews** [joejordanbrown/popover#74]
Firstly I love this component. I'm amazed there isn't an official popover in the angular material library. Great work and filling an important need!

#### Bug, feature request, or proposal:

When I add this component to my angular 8 projects I get a bunch of build errors like

`90     get focusTrapEnabled(): boolean;
           ~~~~~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:91:9 - error TS1086: An accessor cannot be declared in an ambient context.
`

I've had to enabled skipLibCheck in my tsconfig to get it to build. 

Is this an issue with my app or this library? From what I've gathered its related to a breaking change typescript introduce. Any chance the library can be updated to handle more recent typescript versions?

**Comment by PTC-JoshuaMatthews** [comment]
I wasn't able to npm install the latest version

`> @material-extended/mde@3.0.3 postinstall C:\dolphin\PTCCompass.Web.Angular\node_modules\@material-extended\mde
> ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points

'ngcc' is not recognized as an internal or external command,`

**Comment by PTC-JoshuaMatthews** [comment]
I still get the ambient context errors

`ERROR in ../node_modules/@material-extended/mde/lib/popover/popover-trigger.d.ts:64:9 - error TS1086: An accessor cannot be declared in an ambient context.
64     get popoverOpen(): boolean;
           ~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover-trigger.d.ts:79:9 - error TS1086: An accessor cannot be declared in an ambient context.
79     get dir(): Direction;
           ~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:42:9 - error TS1086: An accessor cannot be declared in an ambient context.
42     get positionX(): MdePopoverPositionX;
chunk {polyfills-es5} polyfills-es5.js, polyfills-es5.js.map (polyfills-es5) 531 kB [initial] [rendered]
           ~~~~~~~~~
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 1.18 MB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 4.84 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 340 kB [initial] [rendered]
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:43:9 - error TS1086: An accessor cannot be declared in an ambient context.
Date: 2020-06-15T12:03:42.191Z - Hash: 0791687c50b5319ff64f - Time: 52603ms
43     set positionX(value: MdePopoverPositionX);
           ~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:45:9 - error TS1086: An accessor cannot be declared in an ambient context.
45     get positionY(): MdePopoverPositionY;
           ~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:46:9 - error TS1086: An accessor cannot be declared in an ambient context.
46     set positionY(value: MdePopoverPositionY);
           ~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:48:9 - error TS1086: An accessor cannot be declared in an ambient context.
48     get triggerEvent(): MdePopoverTriggerEvent;
           ~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:49:9 - error TS1086: An accessor cannot be declared in an ambient context.
49     set triggerEvent(value: MdePopoverTriggerEvent);
           ~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:51:9 - error TS1086: An accessor cannot be declared in an ambient context.
51     get enterDelay(): number;
           ~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:52:9 - error TS1086: An accessor cannot be declared in an ambient context.
52     set enterDelay(value: number);
           ~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:54:9 - error TS1086: An accessor cannot be declared in an ambient context.
54     get leaveDelay(): number;
           ~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:55:9 - error TS1086: An accessor cannot be declared in an ambient context.
55     set leaveDelay(value: number);
           ~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:57:9 - error TS1086: An accessor cannot be declared in an ambient context.
57     get overlapTrigger(): boolean;
           ~~~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:58:9 - error TS1086: An accessor cannot be declared in an ambient context.
58     set overlapTrigger(value: boolean);
           ~~~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:60:9 - error TS1086: An accessor cannot be declared in an ambient context.
60     get targetOffsetX(): number;
           ~~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:61:9 - error TS1086: An accessor cannot be declared in an ambient context.
61     set targetOffsetX(value: number);
           ~~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:63:9 - error TS1086: An accessor cannot be declared in an ambient context.
63     get targetOffsetY(): number;
           ~~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:64:9 - error TS1086: An accessor cannot be declared in an ambient context.
64     set targetOffsetY(value: number);
           ~~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:66:9 - error TS1086: An accessor cannot be declared in an ambient context.
66     get arrowOffsetX(): number;
           ~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:67:9 - error TS1086: An accessor cannot be declared in an ambient context.
67     set arrowOffsetX(value: number);
           ~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:69:9 - error TS1086: An accessor cannot be declared in an ambient context.
69     get arrowWidth(): number;
           ~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:70:9 - error TS1086: An accessor cannot be declared in an ambient context.
70     set arrowWidth(value: number);
           ~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:72:9 - error TS1086: An accessor cannot be declared in an ambient context.
72     get arrowColor(): string;
           ~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:73:9 - error TS1086: An accessor cannot be declared in an ambient context.
73     set arrowColor(value: string);
           ~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:78:9 - error TS1086: An accessor cannot be declared in an ambient context.
78     get closeOnClick(): boolean;
           ~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:79:9 - error TS1086: An accessor cannot be declared in an ambient context.
79     set closeOnClick(value: boolean);
           ~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:84:9 - error TS1086: An accessor cannot be declared in an ambient context.
84     get disableAnimation(): boolean;
           ~~~~~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:85:9 - error TS1086: An accessor cannot be declared in an ambient context.
85     set disableAnimation(value: boolean);
           ~~~~~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:90:9 - error TS1086: An accessor cannot be declared in an ambient context.
90     get focusTrapEnabled(): boolean;
           ~~~~~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:91:9 - error TS1086: An accessor cannot be declared in an ambient context.
91     set focusTrapEnabled(value: boolean);
           ~~~~~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:96:9 - error TS1086: An accessor cannot be declared in an ambient context.
96     get focusTrapAutoCaptureEnabled(): boolean;
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:97:9 - error TS1086: An accessor cannot be declared in an ambient context.
97     set focusTrapAutoCaptureEnabled(value: boolean);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:104:9 - error TS1086: An accessor cannot be declared in an ambient context.
104     set panelClass(classes: string);
            ~~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:111:9 - error TS1086: An accessor cannot be declared in an ambient context.
111     get classList(): string;
            ~~~~~~~~~
../node_modules/@material-extended/mde/lib/popover/popover.d.ts:112:9 - error TS1086: An accessor cannot be declared in an ambient context.
112     set classList(classes: string);`

**Comment by linhongyi** [comment]
Same Problem in angular 8 project.  Is there any solution to this problem?

This my package.json

"dependencies": {
    "@angular/animations": "8.2.12",
    "@angular/cdk": "^8.2.3",
    "@angular/common": "8.2.12",
    "@angular/compiler": "8.2.12",
    "@angular/core": "8.2.12",
    "@angular/forms": "8.2.12",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "8.2.12",
    "@angular/platform-browser-dynamic": "8.2.12",
    "@angular/platform-server": "8.2.12",
    "@angular/router": "8.2.12",
    "@material-extended/mde": "^3.0.3",
    "@nguniversal/module-map-ngfactory-loader": "8.1.1",
    "aspnet-prerendering": "^3.0.1",
    "bootstrap": "^4.3.1",
    "core-js": "^3.3.3",
    "hammerjs": "^2.0.8",
    "jquery": "3.4.1",
    "ng-recaptcha": "^5.0.0",
    "oidc-client": "^1.9.1",
    "popper.js": "^1.16.0",
    "rxjs": "^6.5.3",
    "zone.js": "0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.803.14",
    "@angular/cli": "8.3.14",
    "@angular/compiler-cli": "8.2.12",
    "@angular/language-service": "8.2.12",
    "@types/jasmine": "~3.4.4",
    "@types/jasminewd2": "~2.0.8",
    "@types/node": "~12.11.6",
    "codelyzer": "^5.2.0",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "typescript": "3.5.3"
  },
  "optionalDependencies": {
    "node-sass": "^4.12.0",
    "protractor": "~5.4.2",
    "ts-node": "~8.4.1",
    "tslint": "~5.20.0"
  }

**Comment by joejordanbrown** [comment]
@PTC-JoshuaMatthews 
@linhongyi 

Sorry I missed that you're using Angular 8, I should document v3 is for angular 9.

Please try [v2.3.1](https://www.npmjs.com/package/@material-extended/mde/v/2.3.1), let me know if you still have issues with that version and I'll try and set up a repo to test the issue on.

Is there any reason the projects haven't migrated to Angular 9?

**Comment by PTC-JoshuaMatthews** [comment]
@joejordanbrown  v2.3.1 does seem to work on Angular 8, thanks for pointing that out!
 v3 was working fine for me by skipping library check so I may just keep using that.

I have a large app to upgrade with a lot to regression test, and the last time I tried to enable Ivy on angular 8 I got a wall of errors, so not looking forward to 9 where its default and I have to fix them all.  Definitely will upgrade sooner than later but it will be big task so it keeps getting pushed back.

**Comment by linhongyi** [comment]
@joejordanbrown 
 
It's work in Angular 9 project with v2.3.1 version.    

I have to develop client & server project in Visual Studio IDE. The default version of the angular project is 8.0 in Visual Studio. I try to up angular version to 9.0, but has some problem in Visual Studio.

**Comment by joejordanbrown** [comment]
@PTC-JoshuaMatthews

Yeah with a large app switching to Ivy can be a pain. We moved our apps to Ivy a long time back and remember the long weekends fixing everything, I'm hoping the errors are a lot clearer now though because I remember when it was first released debugging was a nightmare.

@linhongyi 

I would recommend removing your reliance with the Visual Studio IDE template, I know it's easy to get started with those types of templates but a lot of the time they can be a pain to maintain and update as the frameworks are updated regularly

I'm not familiar with the IDE Angular template but does it use the Angular CLI?

**Comment by joejordanbrown** [comment]
Btw v3 has lots of bug fixes, which have not been backported to v2. I'm not sure if I have time to maintain v2 but you're welcome to create pull requests if the fixes are required for your projects.

I'm also spending a lot of time updating the internals and there will be API changes when v4 is released in the near future. It will use a cleaner API for configuring, provide a lot more fine-tuning and auto calculating the arrow position offset.
